### ISSUE TITLE
httpx.ConnectError: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by funcfang** [huangwb8/m2w#6]
Hi， 我配置好文件user.json后运行脚本`myblog.py`, 报`httpx.ConnectError: [Errno 11001] getaddrinfo failed` 这个错误大家有遇到过吗？有什么解决方法吗？感谢。
![1677082128566](https://user-images.githubusercontent.com/68361120/220685319-01244e24-5ac6-4fea-a72f-cfa56b16bbf3.png)
![1677082385268](https://user-images.githubusercontent.com/68361120/220686720-5d774819-7944-4715-a298-613e80e35ec5.png)

看样子报错是在`httpx.get()`调用这部分，原因是我本地网络出不去？或者其他原因？配置文件中域名已经是https及账号密码是正确的了。
![1677082098861](https://user-images.githubusercontent.com/68361120/220685207-f3849abf-4893-4d31-a198-549bf50df688.png)
下面是具体的报错：
```
========Website: web01
No legacy json. All markdown files would be treated as brand-new ones.
Create legacy json for new markdowns!
OOPS,The upload failed,Please Try again
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<get_all_articles() done, defined at F:\Note\m2w\m2w\rest_api\articles.py:27> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\backends\sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\backends\sync.py", line 93, in connect_tcp
    with map_exceptions(exc_map):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Note\m2w\m2w\rest_api\articles.py", line 31, in get_all_articles
    article_num = httpx.get(self.url + "wp-json/wp/v2/posts?page=1&per_page=1").headers[
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<get_all_tags() done, defined at F:\Note\m2w\m2w\rest_api\tags.py:28> exception=ConnectError('[Errno 11001] getaddrinfo failed')>
Traceback (most recent call last):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\backends\sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\backends\sync.py", line 93, in connect_tcp
    with map_exceptions(exc_map):
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Note\m2w\m2w\rest_api\tags.py", line 32, in get_all_tags
    tags_num = httpx.get(self.url + "wp-json/wp/v2/tags?page=1&per_page=1").headers[
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\ProgramData\Miniconda3\envs\m2ww\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

进程已结束,退出代码0
```

**Comment by huangwb8** [comment]
@funcfang 

这部分对应的代码是REST API，而不是帐户/密码。如果你使用的是m2w 2.5.1，它默认会使用REST API。

如果你不想使用REST API，应该在config.ini文件中确定`rest_api = false`.

**Comment by FoxSuzuran** [comment]
您好，可以提供下您的配置文件吗，本地测试时尚未遇到此类错误，不需要提供密码

**Comment by funcfang** [comment]
配置文件`user.json`
```
{
    "web01": {
        "domain": "https://funcfang.com",
        "username": "funcfang",
        "password": "",
        "application_password": "",
        "path_markdown": [
            "F:/Note/test"
        ],
        "post_metadata": {
            "category": ["技术"],
            "tag": ["Linux"],
            "status": "publish"
        },
        "path_legacy_json": "/config/legacy"
    }
}
```
此外，我在开启全局代理情况下，报错变得不一样，报ssl错误`httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)`
![image](https://user-images.githubusercontent.com/68361120/220829895-ae6798f6-db35-46ea-8fa6-80198c1122dc.png)

不使用REST API的情况下，也仍然报错，`FAILED to connect to your WordPress website: [Errno 11001] getaddrinfo failed`
![image](https://user-images.githubusercontent.com/68361120/220830051-0fc359ef-993b-4727-9071-1aabe6008aad.png)

原因像是我本地网络的问题。。。

**Comment by funcfang** [comment]
Hi，我在用m2w v2.2.11版本情况下，也是报同样的错误，可能问题是发生在我这边，而不是代码的问题，我自己再排查下。
<img width="536" alt="1677132391521(1)" src="https://user-images.githubusercontent.com/68361120/220832040-ed865a66-35f2-4c5c-80c3-df8d6aa39a32.png">

**Comment by FoxSuzuran** [comment]
@funcfang 老方法的url地址后面要加/,因为没有做特殊处理，请尝试url "https://funcfang.com/"，如若还有问题，请先检查wordpress是否连接正常，因为2.2.1版本挺稳定的

**Comment by FoxSuzuran** [comment]
@funcfang wordpress连接是正常的吗，我访问不了这个域名

**Comment by funcfang** [comment]
> @funcfang 老方法的url地址后面要加/,因为没有做特殊处理，请尝试url "[https://funcfang.com/"，如若还有问题，请先检查wordpress是否连接正常，因为2.2.1版本挺稳定的](https://funcfang.com/%22%EF%BC%8C%E5%A6%82%E8%8B%A5%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E8%AF%B7%E5%85%88%E6%A3%80%E6%9F%A5wordpress%E6%98%AF%E5%90%A6%E8%BF%9E%E6%8E%A5%E6%AD%A3%E5%B8%B8%EF%BC%8C%E5%9B%A0%E4%B8%BA2.2.1%E7%89%88%E6%9C%AC%E6%8C%BA%E7%A8%B3%E5%AE%9A%E7%9A%84)

sorry！是我域名写错了...  我把顶级域名cn写成com了，所以导致没能连接正常...

**Comment by FoxSuzuran** [comment]
> > @funcfang 老方法的url地址后面要加/,因为没有做特殊处理，请尝试url "[https://funcfang.com/"，如若还有问题，请先检查wordpress是否连接正常，因为2.2.1版本挺稳定的](https://funcfang.com/%22%EF%BC%8C%E5%A6%82%E8%8B%A5%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E8%AF%B7%E5%85%88%E6%A3%80%E6%9F%A5wordpress%E6%98%AF%E5%90%A6%E8%BF%9E%E6%8E%A5%E6%AD%A3%E5%B8%B8%EF%BC%8C%E5%9B%A0%E4%B8%BA2.2.1%E7%89%88%E6%9C%AC%E6%8C%BA%E7%A8%B3%E5%AE%9A%E7%9A%84)
> 
> sorry！是我域名写错了... 我把顶级域名cn写成com了，所以导致没能连接正常...

okkk，现在可以正常运行了吗

**Comment by funcfang** [comment]
> > > @funcfang 老方法的url地址后面要加/,因为没有做特殊处理，请尝试url "[https://funcfang.com/"，如若还有问题，请先检查wordpress是否连接正常，因为2.2.1版本挺稳定的](https://funcfang.com/%22%EF%BC%8C%E5%A6%82%E8%8B%A5%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E8%AF%B7%E5%85%88%E6%A3%80%E6%9F%A5wordpress%E6%98%AF%E5%90%A6%E8%BF%9E%E6%8E%A5%E6%AD%A3%E5%B8%B8%EF%BC%8C%E5%9B%A0%E4%B8%BA2.2.1%E7%89%88%E6%9C%AC%E6%8C%BA%E7%A8%B3%E5%AE%9A%E7%9A%84)
> > 
> > 
> > sorry！是我域名写错了... 我把顶级域名cn写成com了，所以导致没能连接正常...
> 
> okkk，现在可以正常运行了吗

可以了！2.2.1版本能够正常上传，但是用2.3版本会上传失败，报错`Reminder from m2w: File F:/Note/test2\Docker.md uploaded failed. Please try again!`
<img width="655" alt="1677134091339" src="https://user-images.githubusercontent.com/68361120/220835652-e2c02a25-879c-4e96-b88f-e0362418816c.png">

**Comment by funcfang** [comment]
顺便分享我在用2.2.1版本上传时遇到的一个问题，`FAILED to connect to your WordPress website: <Fault -32700: 'parse error. not well formed'>` ，这个问题是我服务器没有安装php-xml导致，`sudo apt-get install php-xml -y`安装后即可。更多可以看https://github.com/maxcutler/python-wordpress-xmlrpc/issues/110
<img width="653" alt="7169cb5eec28c0b6a1bc999e886313f" src="https://user-images.githubusercontent.com/68361120/220835810-698d1b88-5cba-4977-8236-b70625ab1377.png">

**Comment by FoxSuzuran** [comment]
@funcfang 我想第一个问题大概是因为已经上传过并且使用了强制上传导致的问题，我会修一下这个bug，第二个确实是考虑不周了，大概会写进下个版本的md里面

**Comment by FoxSuzuran** [comment]
@funcfang 感谢为本项目做出的贡献

**Comment by funcfang** [comment]
> @funcfang 我想第一个问题大概是因为已经上传过并且使用了强制上传导致的问题，我会修一下这个bug，第二个确实是考虑不周了，大概会写进下个版本的md里面

第一个的问题我在新版本有尝试上传新文件，但也仍是失败的，新旧版本配置参数一样，旧版本是成功的。我今晚再看看会不会也是我这边的问题。
<img width="621" alt="1677135213795" src="https://user-images.githubusercontent.com/68361120/220838273-bee9c6f5-173a-4373-a64c-64b65ca04a71.png">
<img width="547" alt="1677135278045(1)" src="https://user-images.githubusercontent.com/68361120/220838428-5d186a57-d349-49e7-95d8-74ac934e04ca.png">

**Comment by FoxSuzuran** [comment]
> 

你确定你用的是应用程序密码而不是登录密码并且没有去掉那几个空格吗

**Comment by funcfang** [comment]
> > 
> 
> 你确定你用的是应用程序密码而不是登录密码并且没有去掉那几个空格吗

我忘记还有应用程序密码这回事了...我直接复制的2.3版本readme下的配置信息。  目前添加应用程序密码后能够正常运行，very OK! 感谢大佬帮我看这么多小问题。
<img width="590" alt="1677135686132" src="https://user-images.githubusercontent.com/68361120/220839555-26e89b99-1e8e-4094-a0ab-ec739f4f5252.png">
